version: '2'
services:
 flink-master:
   image: bde2020/flink-master
   hostname: flink-master
   container_name: flink-master
   ports:
     - "8080:8080"
     - "8081:8081"

 flink-worker:
   image: bde2020/flink-worker
   hostname: flink-worker
   container_name: flink-worker
   environment:
     - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
   depends_on:
      - flink-master
